import React from 'react';

import styles from './styles.module.css';

import Sidebar from "./Sidebar";
import { myAutogeneratedSidebar } from "./Sidebar";

import LibUvPrimitives from "./LibUvPrimitives";
import LuviBuiltins from "./LuviBuiltins";
import EvoLuaExtensions from "./EvoLuaExtensions";

export default function ApiDocumentation() {
	return (
	  <section className={styles.api}>
		<Sidebar/>
		<myAutogeneratedSidebar/>
		<div className="container">
			<h1>API Reference</h1>
			<p>
				In this section, you'll find a high-level overview of the many different APIs that you can use in an evo-based application.
			</p>
			<LibUvPrimitives/>
			<LuviBuiltins/>
			<EvoLuaExtensions/>
			<div className="row"></div>
		</div>
	  </section>
	);
  }
