mindmap
  root((Evo.lua))
    Nonstandard<br/>Lua Libraries
      Text Transformations
      Build Tools
        Ninja File Generation
        Markdown Changelogs
      Unit Testing
        Test Runner
        Assertions
    Lua Bindings for<br/>C and C++ Libraries
      Event Loop:<br/>libuv
      Crypto and TLS:<br/>openssl
      Compression:<br/>zlib
      Regular Expressions:<br/>pcre2
      Pattern Matching:<br/>lpeg
      HTTP Parsing:<br/>llhttp
    LuaJIT Engine
      Foreign Function Interface
      Embedded Bytecode Loader
      Limited Lua 5.2 and 5.3 Compatibility Layer
